disp('file: LookMultipleBoxPlot.m')

rng(1953);   % set seed for reproducibility

n1 = 30; r1 = randn(n1,1);   % standard normal random numbers
n2 = 35; r2 = randn(n2,1);
n3 = 45; r3 = randn(n3,1);
n4 = 39; r4 = randn(n4,1);

figure
boxplot([r1; r2; r3; r4], ...
        [ones(n1,1); 2*ones(n2,1); 3*ones(n3,1); 4*ones(n4,1)], ...
        'Colors','k','Symbol','o')

% Make boxes yellow and slightly transparent
h = findobj(gca,'Tag','Box');
for j = 1:length(h)
    patch(get(h(j),'XData'), get(h(j),'YData'), 'yellow', ...
          'FaceAlpha', 0.3);
end

set(gca,'FontSize',12)
hold on

% Add jittered points (normal jitter around box positions 1,2,3,4)
jitter1 = 1 + 0.05*randn(n1,1);
scatter(jitter1, r1, 15, 'blue', 'filled')

jitter2 = 2 + 0.05*randn(n2,1);
scatter(jitter2, r2, 15, 'blue', 'filled')

jitter3 = 3 + 0.05*randn(n3,1);
scatter(jitter3, r3, 15, 'blue', 'filled')

jitter4 = 4 + 0.05*randn(n4,1);
scatter(jitter4, r4, 15, 'blue', 'filled')

hold off
%  print('-dpng','TransparentMultiBoxplot260218ML.png')
% print('-depsc','TransparentMultiBoxplot260218ML.eps')
% ----------------------------------------------------------------
% Remarks: transparent boxplot for 4 data sets
% The 4 data sets are generated by random sampling from the standard normal distribution.
% boxplot()   can take several (here: 4) data sets
% ----------------------------------------------------------------